### PR TITLE
Hide register logs Issue #105

### PR DESCRIPTION
**Pull request by stellargela**

### CODE REVIEW

**Comment by FMCorz** [comment]
Thank you for your this patch. Unfortunately we cannot change interfaces, so we won't be able to add the methods `can_view_logs` etc. I'm not certain how to best implement additional permissions within the existing framework, I'll have to think about it a bit.

**Comment by stellargela** [comment]
Hi! 
Thank you for your answer. 
I'm looking forward to your ideas and of course, if I can help in any way with the implementation, let me know!

**Comment by goggo24** [comment]
@FMCorz have you found a solution? Do you have an idea? We'd love to use level up & level up pro in our insitution, but cannot use it unless the logs are not visible for teachers. We don't want to make a local patch!

**Comment by FMCorz** [comment]
Hi @goggo24,

We are unsure yet, we want to make sure that we do not bloat the plugin with individual features and are wondering whether this sort of privacy concern should be extended to other parts of the plugin at the same time. For instance, we had a request for the plugin to remove the links to user's profiles.

Is the only privacy concern of yours the ability for teachers to see how students earned their points? If the logs contained less information, would it work? The logs are using for teachers to determine how the points are being earned and hiding them may lead to issues. Are those teachers managing _Level up!_? In that, are they writing the rules, assigning points, etc?

Thank you for your input.

**Comment by goggo24** [comment]
We would like to hide it site-wide. In our solution both cases are possible ;) We need to hide the logs, otherwise we cannot use this plugin and especially level up pro.

**Comment by FMCorz** [comment]
This has been implemented and will be included in the next release. Thank you for your feedback and contributions!

**Pull request closed without merging**
